name: Deploy hello world

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        ref: '${{ github.event.inputs.branch }}'
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'        
        cache: gradle
    - name: Build with Gradle
      run: ./gradlew clean bootJar
      # uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      # with:
      # arguments: clean build -x test --stacktrace -Penv=aws
    - name: Upload JAR
      # We upload to reuse the same jar in the next job.
      uses: actions/upload-artifact@v2
      with:
        # Name of artifact
        name: stage-web.jar
        # Relative path to the jar file
        # path: web/build/libs/web.jar
        path: build/libs/web.jar
        
  deploy:
    needs: build
    name: Deploy Application
    runs-on: ubuntu-latest
    
    steps:
    
      #Download the artifact which was uploaded to the Build Archive's job
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: stage-web.jar

      #Deploy the artifact (JAR) into AWS Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }} #This is referred from GitHub Secrets
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} #This is referred from GitHub Secrets
          use_existing_version_if_available: true
          application_name: ${{ secrets.BEANSTALK_APP_NAME }} #Application name we created in Elastic BeanStalk
          environment_name: dev-env #Environment name we created in Elastic BeanStalk
          version_label: ${{github.SHA}}
          region: us-east-2 #VERY IMPORTANT: AWS Region where initially Applciation was created in AWS EBS. We created in us-east-1 which is N-Virginia
          deployment_package: web.jar #download artifacts from the previous job
